"""Add rewarded credits to usage

Revision ID: 2946c4ffc898
Revises: b95adfc79e09
Create Date: 2026-08-01 12:31:14.621962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2946c4ffc898'
down_revision: Union[str, Sequence[str], None] = 'b95adfc79e09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_usage', sa.Column('reward_credits', sa.Integer(), nullable=True))
    op.add_column('user_usage', sa.Column('reward_ads_watched', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_usage', 'reward_ads_watched')
    op.drop_column('user_usage', 'reward_credits')
    # ### end Alembic commands ###
