"""Add resolution and format fields

Revision ID: 2dfa444a9ba2
Revises: 19da9f969ffa
Create Date: 2026-08-01 10:59:58.769066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dfa444a9ba2'
down_revision: Union[str, Sequence[str], None] = '19da9f969ffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('original_resolution', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('enhanced_resolution', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('output_format', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'output_format')
    op.drop_column('tasks', 'enhanced_resolution')
    op.drop_column('tasks', 'original_resolution')
    # ### end Alembic commands ###
